import { VisualStyle } from './types';

export const VISUAL_STYLES: VisualStyle[] = [
  {
    id: 'aurora',
    name: '极光之境',
    nameEn: 'Aurora Dream',
    category: 'Waves',
    description: 'Bands of cosmic curtains glowing gently across cold night skies, reactive to low-end frequencies.',
    emotion: 'serene',
    gpuReq: 'low',
  },
  {
    id: 'nebula',
    name: '星系云海',
    nameEn: 'Galactic Nebula',
    category: 'Atmosphere',
    description: 'Dynamic interstellar dust clouds morphing under light pressures, reflecting overall energy peaks.',
    emotion: 'serene',
    gpuReq: 'medium',
  },
  {
    id: 'liquid',
    name: '融流幻体',
    nameEn: 'Liquid Flow',
    category: 'Fluid',
    description: 'Viscous cybernetic wave ripples folding gracefully with a metallic fluid shimmer.',
    emotion: 'serene',
    gpuReq: 'low',
  },
  {
    id: 'flow',
    name: '气流纤维',
    nameEn: 'Stellar Flow',
    category: 'Particles',
    description: 'Delicate glowing particles tracing vector force fields across a deep negative space.',
    emotion: 'serene',
    gpuReq: 'medium',
  },
  {
    id: 'bloom',
    name: '盛绽心火',
    nameEn: 'Ethereal Bloom',
    category: 'Organic',
    description: 'Symmetrical sacred geometric petal curves breathing in and out to subtle high notes.',
    emotion: 'tender',
    gpuReq: 'low',
  },
  {
    id: 'flame',
    name: '温暖营火',
    nameEn: 'Primal Flame',
    category: 'Waves',
    description: 'Symphonies of hot glowing wave segments rising symmetrically like a bonfire of frequencies.',
    emotion: 'tender',
    gpuReq: 'low',
  },
  {
    id: 'spectrum',
    name: '环域频谱',
    nameEn: 'Neon Spectrum',
    category: 'Spectrum',
    description: 'High-contrast glowing neon columns reacting closely with instant musical decibels.',
    emotion: 'energized',
    gpuReq: 'low',
  },
  {
    id: 'pulse',
    name: '回旋共振',
    nameEn: 'Vibrant Pulse',
    category: 'Pulse',
    description: 'A glowing circular core shooting radiant light filaments outward on sudden bass beats.',
    emotion: 'energized',
    gpuReq: 'medium',
  },
  {
    id: 'vortex',
    name: '重力漩涡',
    nameEn: 'Sonic Vortex',
    category: 'Vortex',
    description: 'Spiraling gravity corridors pulled inward towards a singularity point during heavy sub-bass.',
    emotion: 'energized',
    gpuReq: 'high',
  },
  {
    id: 'cosmic',
    name: '深空尘埃',
    nameEn: 'Cosmic Field',
    category: 'Atmosphere',
    description: 'Floating cosmic particles responding with orbital speed alignments in serene dark vacuums.',
    emotion: 'focused',
    gpuReq: 'low',
  },
  {
    id: 'neural',
    name: '神经链接',
    nameEn: 'Neural Synapsis',
    category: 'Network',
    description: 'Interactive bio-electric network nodes glowing as sound frequencies send charge pulses.',
    emotion: 'focused',
    gpuReq: 'medium',
  },
  {
    id: 'crystal',
    name: '棱镜秩序',
    nameEn: 'Prism Lattice',
    category: 'Geometry',
    description: 'Symmetric crystalline structures rotating cleanly with math-driven light reflections.',
    emotion: 'focused',
    gpuReq: 'low',
  },
  {
    id: 'matrix',
    name: '量子雨林',
    nameEn: 'Quantum Rain',
    category: 'Matrix',
    description: 'Columns of glowing digit stream rains descending faster with energetic acoustic waves.',
    emotion: 'focused',
    gpuReq: 'low',
  },
];
